package com.orderon;

public enum ExpenseType {

	INVENTORY, ADVANCE, FLOAT, RENT, ELECTRICITY_BILL, GAS_BILL, PETROL, LABOUR, TELEPHONE_BILL, MOBILE_RECHARGE, INTERNET,
	SOFTWARE, COMPUTER_HARDWARE, REPAIRS, OTHERS, CASH_LIFT, TIPS;
}
