package com.orderon.commons;

import java.text.ParseException;

import com.orderon.dao.AccessManager;

public class ShortForm{
    public static void main(String args[]) throws ParseException {

		String alltitle = "TEA,"
				+"COFFEE,"
				+"KESARI UKALA,"
				+"BATATA  VADA,"
				+"STEAM IDLI .,"
				+"IDLI FRY,"
				+"DAHI IDLI,"
				+"KANDA POHA,"
				+"KANDA BAJI,"
				+"MISAL,"
				+"MISAL PAV,"
				+"DAHI MISAL,"
				+"DAHI VADA,"
				+"PURI BHAJI,"
				+"BREAD MASALA,"
				+"PANEER PAKODA,"
				+"VADA PAV,"
				+"IDLI WADA,"
				+"SHEERA,"
				+"PINEAPPLE SHIRA,"
				+"SINGLE WADA USAL,"
				+"SABUDANA WADA,"
				+"SABUDANA KHICHIDI,"
				+"CHEESE SADA DOSA,"
				+"SADA DOSA,"
				+"MASALA DOSA,"
				+"UTTAPAM,"
				+"MASALA UTTAPAM,"
				+"ONION UTTAPAM,"
				+"TOMATO UTTAPAM,"
				+"SPRING DOSA,"
				+"SCHEZWAN NOODLES DOSA,"
				+"SCHEZWAN DOSA,"
				+"POLA USAL,"
				+"EXTRA CHEESE /BUTTER,"
				+"CHEESE RAWA SADA,"
				+"VEG SANDWICH,"
				+"VEG TOAST S/W,"
				+"PLAIN CHEESE S/W,"
				+"PLAIN CHEESE TOAST S/W,"
				+"BREAD BTR,"
				+"VEG CHEESE S/W,"
				+"VEG CHEESE TOAST S/W.,"
				+"CLUB S/W,"
				+"DAL KHICHDI,"
				+"CURD RICE,"
				+"TOMATO KHICHDI,"
				+"MASALAPAPAD,"
				+"VEG PULAV,"
				+"SWEET LASSI,"
				+"BUTTER MILK,"
				+"FRESH LIME WATER,"
				+"GINGER LEMON,"
				+"KOKAM SHARBAT,"
				+"AWLA SHARBAT,"
				+"MINERAL WATER,"
				+"VEG SWEET CORN SOUP,"
				+"MANCHOW,"
				+"HOT & SOUR,"
				+"VEG CLEAR,"
				+"VEG MANCHURIAN,"
				+"PANEER SALT  PEPPER,"
				+"PANEER CRISPY,"
				+"PANEER MANCHURIAN,"
				+"CORN SALT PEPPER,"
				+"CORN CRISPY,"
				+"PANEER CHILLY,"
				+"IDLI CHILLY DRY,"
				+"FRIED RICE,"
				+"SCHEZWAN F/R,"
				+"PEKING F/R,"
				+"HONG F/R,"
				+"POT RICE,"
				+"STEW RICE,"
				+"PAN F/R,"
				+"AMERICAN CHOPSUEY,"
				+"TRIPLE SCHE/RICE,"
				+"SINGAPORE NOODLES,"
				+"HAKKA NOODLES,"
				+"CHOWMEIN NOODELS,"
				+"NEER DOSA,"
				+"GOLI BHAJI,"
				+"MOSAMBI JUICE,"
				+"ORANGE JUICE,"
				+"GANGA JAMUNA,"
				+"WATERMELON,"
				+"PINEAPPLE JUICE,"
				+"WADA USAL,"
				+"SINGLE PAV,"
				+"MEDU WADA,"
				+"SAMBHAR,"
				+"SINGLE POTOTO WADA,"
				+"CUTING TEA,"
				+"SMALL WATER,"
				+"SPL BHAJI,"
				+"CHAPATI,"
				+"RAWA SADA DOSA,"
				+"RAWA MASALA DOSA,"
				+"SPECIAL THALI,"
				+"PURI LUNCH,"
				+"DAAL RICE FULL,"
				+"DAAL RICE HALF,"
				+"CHANNA MASALA,"
				+"ALOO MUTTER,"
				+"VEG BIRYANI,"
				+"ROASTED PAPAD,"
				+"EXTRA,"
				+"PANEER BIRYANI,"
				+"COLDRINK,"
				+"SOFT DRINK,"
				+"DAL TADKA,"
				+"DAL FRY,"
				+"VEG CHEESE PIZZA,"
				+"PANNER TIKKA MASALA,"
				+"MANCHUAN RICE,"
				+"PURI PLATE,"
				+"EXTRA,"
				+"DAL WADA,"
				+"MIX VEG,"
				+"RAWA BUTTER SADA,"
				+"BUTTER SADA DOSA,"
				+"USAL PAV,"
				+"DAHI MISAL PAV,"
				+"BATATA WADA USAL,"
				+"PLATE POLA,"
				+"EXTRA PAV,"
				+"SWEET KACHORI,"
				+"FINGER CHIPS,"
				+"DAHI VADA,"
				+"KOTHIMBIR VADE,"
				+"MYSORE SADA DOSA,"
				+"MYSORE MASALA DOSA,"
				+"ONION RAVA SADA DOSA,"
				+"ONION RAVA MASALA DOSA,"
				+"PALAK SADA DOSA,"
				+"PALAK MASALA DOSA,"
				+"PLAIN UTTAPAM,"
				+"TOMATO ONION UTTAPAM,"
				+"TOMATO OMELET,"
				+"SCHEZWAN MASALA DOSA,"
				+"CHUTNEY S/W,"
				+"VEG GRILLED S/W,"
				+"VEG CHEESE GRILLED S/W,"
				+"CHEESE GRILLED S/W,"
				+"TOAST BUTTER,"
				+"BREAD SLIOCE(2),"
				+"JAIN PIZZA,"
				+"CHEESE PIZZA,"
				+"COLD COFFEE,"
				+"BANANA MILKSHAKE,"
				+"ROSE MILKSHAKE,"
				+"TOMATO SOUP,"
				+"PALAK SOUP,"
				+"SWEETCORN SOUP(PLAIN),"
				+"HARA BARA KEBAB,"
				+"VEG CRISPY,"
				+"VEG SPRING ROLL,"
				+"VEG LOLLY POP,"
				+"GOBI MANCHRIAN,"
				+"MUSHROOM MUNCHURIAN,"
				+"MIUSHROOM CHILLY,"
				+"PANEER SCHEZWAN DRY,"
				+"PANEER SPRING ROLL,"
				+"PANEER TIKKA DRY,"
				+"BHARAT SPECIAL VEGETABLE,"
				+"ALOO METHI,"
				+"ALOO JEERA,"
				+"ALOO PALAK,"
				+"PLAIN PALAK,"
				+"LASUNI PALAK,"
				+"VEG MAKHANWALA,"
				+"VEG KOLHAPURI,"
				+"VEG JALFREZI,"
				+"VEG HYDERABADI,"
				+"VEG KOFTA,"
				+"MALAI KOFTA,"
				+"NAVRATNA KURMA,"
				+"BHENDI MASALA,"
				+"BHENDI M/S FRY(DRY),"
				+"VEG ROYAL MARATHA,"
				+"VEG MAHARAJ,"
				+"VEG CHILLY MILLY,"
				+"GREEN PEAS MASALA,"
				+"VEG CHINGARI,"
				+"PANEER PALAK,"
				+"PANEER BUTTER MASALA,"
				+"PANEER PASANDA,"
				+"PANEER MASALA,"
				+"PANEER MUTTER,"
				+"PANEER BURJI,"
				+"PANEER MUSHROOM MASALA,"
				+"PANEER LAJAWAB,"
				+"PANEER CHINGARI,"
				+"DAL KOLHAPURI,"
				+"BUTTER DAL FRY,"
				+"TANDOORI ROTI,"
				+"BUTTER ROTI,"
				+"NAAN,"
				+"BUTTER NAAN,"
				+"PARATHA,"
				+"BUTTER PARATHA,"
				+"KULCHA,"
				+"BUTTER KULCHA,"
				+"ALOO PARATHA,"
				+"STUFF PARATHA,"
				+"STEAM RICE,"
				+"PLAIN RICE,"
				+"GREEN PEAS PULAV,"
				+"KASHMIRI PULAV,"
				+"PALAK KHICHDI,"
				+"LEMON RICE,"
				+"VEG RAITA,"
				+"BOONDI RAITA,"
				+"CURD,"
				+"GREEN SALAD,"
				+"FRY PAPAD,"
				+"VEG MUNCHURIAN RICE,"
				+"VEG COMBINATION RICE,"
				+"VEG TRIPLE SCHEZWAN FRIED RICE,"
				+"VEG BURNT CHILLI RICE,"
				+"VEG SCHEZWAN NOODLES,"
				+"VEG TRIPLE SCHEZWAN NOODLES,"
				+"PAV BHAJI,"
				+"JAIN PAV BHAJI,"
				+"CHEESE PAV BHAJI,"
				+"JAIN CHEESE PAV BHAJI,"
				+"ONLY BHAJI,"
				+"JAIN ONLY BHAJI,"
				+"EXTRA BUTTER PAV,"
				+"ROSE FALOODA,"
				+"KESAR FALOODA,"
				+"CHAPATI LUNCH,"
				+"ROTI LUNCH,"
				+"FRESH LIME SODA,"
				+"UPMA,"
				+"Jeera Rice";
		
		String[] titles = alltitle.split(",");
		
		for (String t : titles) {
			generateShortForm(t);
			//System.out.println(AccessManager.toTitleCase(t));
		}
		
	}
    private static void generateShortForm(String title) {

		String[] sf = title.split(" ");
		StringBuilder out = new StringBuilder();
	
		for (int i = 0; i < sf.length; i++) {
			if (sf[i].length() > 0)
				out.append(sf[i].substring(0, 1).toUpperCase());
		}
		System.out.println(out.toString());
		
    }
    
	private static void camelise(String title) {

		String[] sf = title.split(" ");
		StringBuilder out = new StringBuilder();
	
		for (int i = 0; i < sf.length; i++) {
			if(sf[i].length()<2)
				continue;
			if (sf[i].length() > 0)
				out.append(sf[i].substring(0, 1).toUpperCase());
			out.append(sf[i].substring(1, sf[i].length()).toLowerCase());
			out.append(" ");
		}
		System.out.println(out.toString());
	}
	
}